title: Christine Hathaway # your name (or website title) here
logo: #"/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Project Portfolio 
  <br><br>
  Master of Science in Data Science at Bellevue University
  <br><br>
  #<a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-merlot
google_analytics: #UA-000000-0 # your Google Analytics tracking ID here
