title: Christine Hathaway # your name (or website title) here
logo: "/images/bio-photo2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Academic Portfolio Data Science Program
  <br><br>
  
theme: jekyll-theme-merlot
google_analytics: #UA-000000-0 # your Google Analytics tracking ID here
